export enum LeadStatus {
  NUEVO = 'NUEVO',
  CONTACTADO = 'CONTACTADO',
  VISITA_AGENDADA = 'VISITA_AGENDADA',
  VISITA_REALIZADA = 'VISITA_REALIZADA',
  NEGOCIACION = 'NEGOCIACION',
  GANADO = 'GANADO',
  PERDIDO = 'PERDIDO',
}

export enum LeadOrigin {
  WEB = 'WEB',
  WHATSAPP = 'WHATSAPP',
  PORTAL = 'PORTAL',
  REFERIDO = 'REFERIDO',
  OTRO = 'OTRO',
}
