export enum MaintenanceStatus {
  PENDIENTE = 'PENDIENTE',
  EN_PROGRESO = 'EN_PROGRESO',
  ESPERANDO_REPUESTOS = 'ESPERANDO_REPUESTOS',
  RESUELTO = 'RESUELTO',
  CERRADO = 'CERRADO',
}

export enum MaintenancePriority {
  BAJA = 'BAJA',
  MEDIA = 'MEDIA',
  ALTA = 'ALTA',
  URGENTE = 'URGENTE',
}

export enum MaintenanceCategory {
  PLOMERIA = 'PLOMERIA',
  ELECTRICIDAD = 'ELECTRICIDAD',
  PINTURA = 'PINTURA',
  LIMPIEZA = 'LIMPIEZA',
  SEGURIDAD = 'SEGURIDAD',
  GENERAL = 'GENERAL',
}
