export enum PropertyStatus {
  DISPONIBLE = 'DISPONIBLE',
  OCUPADA = 'OCUPADA',
  MANTENIMIENTO = 'MANTENIMIENTO',
}

export enum PropertyType {
  APARTAMENTO = 'APARTAMENTO',
  DUPLEX = 'DUPLEX',
  CASA = 'CASA',
  OFICINA = 'OFICINA',
  LOCAL = 'LOCAL',
}
